- hosts: all
  gather_facts: false
  tasks:
    - name: debug
      debug:  
        msg: "Hello"

    - name: debug
      debug:
        msg: "{{ hostvars }}"

    - name: debug
      debug:
        msg: "{{ tt }}"
